/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailSplatRouteImport } from './routes/detail.$'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailSplatRoute = DetailSplatRouteImport.update({
  id: '/detail/$',
  path: '/detail/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/detail/$': typeof DetailSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/detail/$': typeof DetailSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/detail/$': typeof DetailSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/packages' | '/detail/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/packages' | '/detail/$'
  id: '__root__' | '/' | '/packages' | '/detail/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackagesRoute: typeof PackagesRoute
  DetailSplatRoute: typeof DetailSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$': {
      id: '/detail/$'
      path: '/detail/$'
      fullPath: '/detail/$'
      preLoaderRoute: typeof DetailSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackagesRoute: PackagesRoute,
  DetailSplatRoute: DetailSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
