# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.3.0

    - name: Install pnpm
      run: npm install pnpm -g

    - name: Install dependencies
      run: |
        cd web
        pnpm install --frozen-lockfile

    - name: Build web
      run: |
        cd web
        pnpm build

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build project
      run: GOOS=linux GOARCH=amd64 go build -o verda ./main.go

    - name: Archive Artifacts
      run: tar -czvf verda-amd64.tar.gz verda  # 创建一个压缩文件以存储构建结果

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: verda-amd64
        path: verda-amd64.tar.gz  # 上传构建结果
